### ISSUE TITLE
Why can we not specify a custom size?

### ISSUE THREAD

**Issue by alexpirine** [PolymerElements/paper-spinner#74]
Hello,

Is there a reason why the size of the spinner is hard-coded and cannot be changed?

Thank you,

Alexander

**Comment by keanulee** [comment]
You can override `width/height` with your own CSS where you use the element:

```css
paper-spinner {
  width: 40px;
  height: 40px;
}
```
